name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sirius-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: limit make jobs to 1
      run: sed -i 's/MAKEFLAGS=-j/MAKEFLAGS=-j1/g' Dockerfile
    - name: make docker
      run: make docker
