name: testdeployment

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sirius-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: prepare network
      run: make network
    - name: Test
      run: make run-ixiac-test