name: Sirius-CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'sirius-pipeline/**'
      - '!sirius-pipeline/Dockerfile'
      - '!sirius-pipeline/**.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'sirius-pipeline/**'
      - '!sirius-pipeline/Dockerfile'
      - '!sirius-pipeline/**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      docker_flags: d -u root
    defaults:
      run:
        working-directory: ./sirius-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Install SAI submodule
      run: git submodule update --init
    - name: Pull docker bmv2 image
      run: make docker-pull
    - name: Build P4 software switch (bmv2) and P4RT
      run: DOCKER_FLAGS=$docker_flags make p4
    - name: Generate SAI API
      run: DOCKER_FLAGS=$docker_flags make sai
    - name: Build vnet_out test, verifies libsai binding to c++
      run: DOCKER_FLAGS=$docker_flags make test
    - name: Prepare network
      run: DOCKER_FLAGS=$docker_flags make network
    - name: Run P4 software switch (bmv2)
      run: DOCKER_FLAGS=$docker_flags make run-switch
    - name: Test SAI
      run: make run-test
    - name: Ixia-c Traffic Generator test
      run: make run-ixiac-test