name: Sirius-CI

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - 'documentation/**'
      - 'slides/**'
      - 'images/**'
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'documentation/**'
      - 'slides/**'
      - 'images/**'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sirius-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: make docker
    - name: Build P4 software switch (bmv2) and P4RT
      run: make bmv2/sirius_pipeline.bmv2/sirius_pipeline.json
    - name: Generate SAI API
      run: make sai
    - name: Build vnet_out test, verifies libsai bidning to c++
      run: make test
    - name: Prepare network
      run: make network
    - name: Run P4 software switch (bmv2)
      run: make run-switch
    - name: Test SAI
      run: make run-test
    - name: Ixia-c Traffic Generator test
      run: make run-ixiac-test